---
- name: Create znc group
  become: true
  group:
    name: "{{ znc_user }}"
    state: present

- name: Create znc user
  become: true
  user:
    name: "{{ znc_user }}"
    state: present
    group: "{{ znc_user }}"

- name: install package
  become: true
  apt:
    name: "{{ znc_package }}"
    state: present
  register: _znc_package_task
