---
- name: Create znc group
  become: true
  group:
    name: "{{ znc_user }}"
    state: present

- name: Create znc user
  become: true
  user:
    name: "{{ znc_user }}"
    state: present
    group: "{{ tour_user }}"

- name: install package
  become: true
  apt:
    name: "{{ znc_package }}"
    state: present
  register: _znc_package_task

- name: initialize znc configuration
  become: true
  become_user: "{{ znc_user }}"
  shell: znc --makeconf
  when: _znc_package_task is changed
